// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4i0gEPvfH4LCzTW5NAGtCSQ8u58_vbQ0',
    appId: '1:713655422766:web:01330ff00729498b6074bf',
    messagingSenderId: '713655422766',
    projectId: 'carecue-ssupti',
    authDomain: 'carecue-ssupti.firebaseapp.com',
    storageBucket: 'carecue-ssupti.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbdiDXE53LtCYnBBMKPWj_pHjKRAkS2F0',
    appId: '1:713655422766:android:7275aef2a50181596074bf',
    messagingSenderId: '713655422766',
    projectId: 'carecue-ssupti',
    storageBucket: 'carecue-ssupti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx37jaHF1__051A3UTPxzF4Q2lgxPCAX4',
    appId: '1:713655422766:ios:e82319237113e7626074bf',
    messagingSenderId: '713655422766',
    projectId: 'carecue-ssupti',
    storageBucket: 'carecue-ssupti.firebasestorage.app',
    iosBundleId: 'com.example.carecue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx37jaHF1__051A3UTPxzF4Q2lgxPCAX4',
    appId: '1:713655422766:ios:e82319237113e7626074bf',
    messagingSenderId: '713655422766',
    projectId: 'carecue-ssupti',
    storageBucket: 'carecue-ssupti.firebasestorage.app',
    iosBundleId: 'com.example.carecue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4i0gEPvfH4LCzTW5NAGtCSQ8u58_vbQ0',
    appId: '1:713655422766:web:aeaeb52150e1a1436074bf',
    messagingSenderId: '713655422766',
    projectId: 'carecue-ssupti',
    authDomain: 'carecue-ssupti.firebaseapp.com',
    storageBucket: 'carecue-ssupti.firebasestorage.app',
  );
}
